site_name: TestStack.White
theme: readthedocs
repo_url: https://github.com/TestStack/White

pages:
- Home: index.md
- Changelog: ChangeLog.md
- Configuration: Configuration.md
- Getting Started: GettingStarted.md
- UI Items: UIItems.md
- Windows: Windows.md
- FAQ: FAQ.md
- Screen Objects:
    - Screen Objects: Screen Objects\Index.md
    - Screen Repository: Screen Objects\ScreenRepository.md
    - Screens UIItems And Entities: Screen Objects\ScreensUIItemsAndEntities.md
    - Refactoring to use Screen Objects: Screen Objects\RefactoringToUseScreenObjects.md
    - Test Entities: Screen Objects\TestEntities.md
- Advanced Topics:
    - Index: Index.md
    - Continuous Integration: Advanced Topics\ContinuousIntegration.md
    - Custom UI Items: Advanced Topics\CustomUIItems.md
    - Localisation: Advanced Topics\Localisation.md
    - Mouse and keyboard: Advanced Topics\MouseAndKeyboard.md
    - Search Depth: Advanced Topics\SearchDepth.md
    - Waiting: Advanced Topics\Waiting.md
    - Third party controls: Advanced Topics\ThirdPartyControls.md
    - Position based search: Advanced Topics\PositionBasedSearch.md
    - UIA v3: Advanced Topics\UIAv3.md